name: "Hello Actions"
description: "Greet someone"
author: "scott.ankin@devopsgroup.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "World"

  runs:
    using: "docker"
    image: "Dockerfile"

  branding:
    icon: "mic"
    color: "purple"